/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AssetEventType = "enter" | "exit";

export type AssetInstanceFanoutMode = "global_per_item" | "scoped_by_source";

export type AssetMaterializationStatus = "cancelled" | "error" | "in_progress" | "success";

export type AssetSlug =
  | "post_corpus_for_segment"
  | "segment_followed"
  | "segment_followers"
  | "segment_mutuals"
  | "segment_specified_users"
  | "segment_unreciprocated_followed";

export type FollowsSyncMode = "full_refresh" | "incremental";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type IngestKind =
  | "ifttt_webhook_new_follow"
  | "twitterio_api_posts_by_ids"
  | "twitterio_api_user_followers"
  | "twitterio_api_user_followings"
  | "twitterio_api_users_by_ids"
  | "twitterio_api_users_posts";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type SyncRunStatus = "cancelled" | "error" | "in_progress" | "success";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AssetInstanceFanoutRoots {
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  fanout_mode: AssetInstanceFanoutMode;
  id: Generated<bigint>;
  source_instance_id: bigint;
  target_asset_slug: AssetSlug;
}

export interface AssetInstanceRoots {
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  id: Generated<bigint>;
  instance_id: bigint;
}

export interface AssetInstances {
  asset_slug: AssetSlug;
  current_membership_materialization_id: bigint | null;
  id: Generated<bigint>;
  params_hash: string;
  params_hash_version: Generated<number>;
  params_id: bigint;
}

export interface AssetMaterializationDependencies {
  dependency_materialization_id: bigint;
  materialization_id: bigint;
}

export interface AssetMaterializationRequests {
  materialization_id: bigint;
  requested_by_materialization_id: bigint;
}

export interface AssetMaterializations {
  asset_instance_id: bigint;
  asset_slug: AssetSlug;
  completed_at: Timestamp | null;
  dependency_revisions_hash: string;
  dependency_revisions_hash_version: Generated<number>;
  error_payload: Json | null;
  id: Generated<bigint>;
  inputs_hash: string;
  inputs_hash_version: Generated<number>;
  output_revision: Generated<bigint>;
  started_at: Generated<Timestamp>;
  status: Generated<AssetMaterializationStatus>;
  trigger_reason: string | null;
}

export interface AssetParams {
  asset_slug: AssetSlug;
  fanout_source_params_hash: string | null;
  fanout_source_params_hash_version: number | null;
  id: Generated<bigint>;
  params_hash: string;
  params_hash_version: Generated<number>;
}

export interface FollowersSyncRuns {
  completed_at: Timestamp | null;
  cursor_exhausted: Generated<boolean>;
  ingest_event_id: bigint;
  last_api_error: string | null;
  last_api_status: string | null;
  last_http_request: Json | null;
  last_http_response: Json | null;
  status: Generated<SyncRunStatus>;
  sync_mode: Generated<FollowsSyncMode>;
  target_user_id: bigint;
}

export interface FollowingsSyncRuns {
  completed_at: Timestamp | null;
  cursor_exhausted: Generated<boolean>;
  ingest_event_id: bigint;
  last_api_error: string | null;
  last_api_status: string | null;
  last_http_request: Json | null;
  last_http_response: Json | null;
  source_user_id: bigint;
  status: Generated<SyncRunStatus>;
  sync_mode: Generated<FollowsSyncMode>;
}

export interface Follows {
  follower_id: bigint;
  is_deleted: Generated<boolean>;
  target_id: bigint;
}

export interface FollowsMeta {
  follower_id: bigint;
  id: Generated<bigint>;
  ingest_event_id: bigint;
  ingest_kind: IngestKind;
  target_id: bigint;
  updated_at: Generated<Timestamp>;
}

export interface IngestEvents {
  created_at: Generated<Timestamp>;
  id: Generated<bigint>;
  ingest_kind: IngestKind;
}

export interface PostCorpusEnterEvents {
  event_type: AssetEventType | null;
  id: bigint | null;
  is_first_appearance: boolean | null;
  materialization_id: bigint | null;
  post_id: bigint | null;
  recorded_at: Timestamp | null;
}

export interface PostCorpusEvents {
  event_type: AssetEventType;
  id: Generated<bigint>;
  is_first_appearance: boolean | null;
  materialization_id: bigint;
  post_id: bigint;
  recorded_at: Generated<Timestamp>;
}

export interface PostCorpusExitEvents {
  event_type: AssetEventType | null;
  id: bigint | null;
  is_first_appearance: boolean | null;
  materialization_id: bigint | null;
  post_id: bigint | null;
  recorded_at: Timestamp | null;
}

export interface PostCorpusForSegmentParams {
  asset_params_id: bigint;
  source_segment_params_id: bigint;
}

export interface PostCorpusMembershipSnapshots {
  instance_id: bigint;
  materialization_id: bigint;
  post_id: bigint;
  recorded_at: Generated<Timestamp>;
}

export interface Posts {
  author_id: bigint;
  id: bigint;
  is_deleted: Generated<boolean>;
  lang: string | null;
  posted_at: Timestamp;
  raw_json: Json | null;
  text: string | null;
}

export interface PostsMeta {
  id: Generated<bigint>;
  ingest_event_id: bigint;
  post_id: bigint;
  updated_at: Generated<Timestamp>;
}

export interface PostsSyncRunRequestedByMaterializations {
  posts_sync_run_id: bigint;
  requested_by_materialization_id: bigint;
}

export interface PostsSyncRuns {
  completed_at: Timestamp | null;
  cursor_exhausted: Generated<boolean>;
  ingest_event_id: bigint;
  last_api_error: string | null;
  last_api_status: string | null;
  last_http_request: Json | null;
  last_http_response: Json | null;
  status: Generated<SyncRunStatus>;
  synced_since: Timestamp | null;
}

export interface PostsSyncRunTargetUsers {
  posts_sync_run_id: bigint;
  target_user_id: bigint;
}

export interface SchedulerPlannerEvents {
  created_at: Generated<Timestamp>;
  decision: string;
  id: Generated<bigint>;
  job_id: string;
  planned_for: Timestamp | null;
  planner_run_id: string | null;
  reason: string | null;
  target_id: string | null;
  target_params: string | null;
}

export interface SchedulerPolicyOverrides {
  cadence_seconds: bigint | null;
  disabled: Generated<boolean>;
  id: Generated<bigint>;
  jitter_seconds: number | null;
  job_id: string;
  max_parallel_per_target: number | null;
  max_retries: number | null;
  reason: string | null;
  target_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SegmentEnterEvents {
  event_type: AssetEventType | null;
  id: bigint | null;
  is_first_appearance: boolean | null;
  materialization_id: bigint | null;
  recorded_at: Timestamp | null;
  user_id: bigint | null;
}

export interface SegmentEvents {
  event_type: AssetEventType;
  id: Generated<bigint>;
  is_first_appearance: boolean | null;
  materialization_id: bigint;
  recorded_at: Generated<Timestamp>;
  user_id: bigint;
}

export interface SegmentExitEvents {
  event_type: AssetEventType | null;
  id: bigint | null;
  is_first_appearance: boolean | null;
  materialization_id: bigint | null;
  recorded_at: Timestamp | null;
  user_id: bigint | null;
}

export interface SegmentFollowedParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface SegmentFollowersParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface SegmentMembershipSnapshots {
  instance_id: bigint;
  materialization_id: bigint;
  recorded_at: Generated<Timestamp>;
  user_id: bigint;
}

export interface SegmentMutualsParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface SegmentSpecifiedUsersInputs {
  instance_id: bigint;
  user_id: bigint;
}

export interface SegmentSpecifiedUsersParams {
  asset_params_id: bigint;
  stable_key: string;
}

export interface SegmentUnreciprocatedFollowedParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface PostsByIdsIngestRunRequestedPosts {
  post_id: bigint;
  posts_by_ids_ingest_run_id: bigint;
}

export interface PostsByIdsIngestRuns {
  completed_at: Timestamp | null;
  ingest_event_id: bigint;
  last_api_error: string | null;
  last_api_status: string | null;
  last_http_request: Json | null;
  last_http_response: Json | null;
  status: Generated<SyncRunStatus>;
}

export interface UserHandleHistory {
  id: Generated<bigint>;
  ingest_event_id: bigint | null;
  new_handle: string;
  previous_handle: string;
  recorded_at: Generated<Timestamp>;
  user_id: bigint;
}

export interface Users {
  affiliates_highlighted_label: Json | null;
  automated_by: string | null;
  bio: string | null;
  bio_entities: Json | null;
  cover_image_url: string | null;
  display_name: string | null;
  favourites_count: bigint | null;
  followers_count: bigint | null;
  following_count: bigint | null;
  handle: string | null;
  handle_norm: Generated<string | null>;
  id: bigint;
  is_automated: boolean | null;
  is_blue_verified: boolean | null;
  is_deleted: Generated<boolean>;
  is_translator: boolean | null;
  last_ingest_event_id: bigint | null;
  last_ingest_kind: IngestKind | null;
  last_updated_at: Timestamp;
  location: string | null;
  media_count: bigint | null;
  pinned_tweet_ids: string[] | null;
  possibly_sensitive: boolean | null;
  profile_image_url: string | null;
  profile_url: string | null;
  statuses_count: bigint | null;
  unavailable: boolean | null;
  unavailable_message: string | null;
  unavailable_reason: string | null;
  user_created_at: Timestamp | null;
  verified_type: string | null;
  withheld_countries: string[] | null;
}

export interface UsersByIdsIngestRunRequestedUsers {
  user_id: bigint;
  users_by_ids_ingest_run_id: bigint;
}

export interface UsersByIdsIngestRuns {
  completed_at: Timestamp | null;
  ingest_event_id: bigint;
  last_api_error: string | null;
  last_api_status: string | null;
  last_http_request: Json | null;
  last_http_response: Json | null;
  status: Generated<SyncRunStatus>;
}

export interface UsersMeta {
  id: Generated<bigint>;
  ingest_event_id: bigint;
  ingest_kind: IngestKind;
  updated_at: Generated<Timestamp>;
  user_id: bigint;
}

export interface WebhookFollowEvents {
  follower_handle: string | null;
  follower_user_id: bigint | null;
  ingest_event_id: bigint;
  raw_payload: Json | null;
  target_user_id: bigint;
}

export interface WorkerHeartbeats {
  last_heartbeat_at: Generated<Timestamp>;
  service: string;
  started_at: Generated<Timestamp>;
  worker_id: string;
}

export interface DB {
  asset_instance_fanout_roots: AssetInstanceFanoutRoots;
  asset_instance_roots: AssetInstanceRoots;
  asset_instances: AssetInstances;
  asset_materialization_dependencies: AssetMaterializationDependencies;
  asset_materialization_requests: AssetMaterializationRequests;
  asset_materializations: AssetMaterializations;
  asset_params: AssetParams;
  followers_sync_runs: FollowersSyncRuns;
  followings_sync_runs: FollowingsSyncRuns;
  follows: Follows;
  follows_meta: FollowsMeta;
  ingest_events: IngestEvents;
  post_corpus_enter_events: PostCorpusEnterEvents;
  post_corpus_events: PostCorpusEvents;
  post_corpus_exit_events: PostCorpusExitEvents;
  post_corpus_for_segment_params: PostCorpusForSegmentParams;
  post_corpus_membership_snapshots: PostCorpusMembershipSnapshots;
  posts: Posts;
  posts_meta: PostsMeta;
  posts_sync_run_requested_by_materializations: PostsSyncRunRequestedByMaterializations;
  posts_sync_run_target_users: PostsSyncRunTargetUsers;
  posts_sync_runs: PostsSyncRuns;
  scheduler_planner_events: SchedulerPlannerEvents;
  scheduler_policy_overrides: SchedulerPolicyOverrides;
  segment_enter_events: SegmentEnterEvents;
  segment_events: SegmentEvents;
  segment_exit_events: SegmentExitEvents;
  segment_followed_params: SegmentFollowedParams;
  segment_followers_params: SegmentFollowersParams;
  segment_membership_snapshots: SegmentMembershipSnapshots;
  segment_mutuals_params: SegmentMutualsParams;
  segment_specified_users_inputs: SegmentSpecifiedUsersInputs;
  segment_specified_users_params: SegmentSpecifiedUsersParams;
  segment_unreciprocated_followed_params: SegmentUnreciprocatedFollowedParams;
  posts_by_ids_ingest_run_requested_posts: PostsByIdsIngestRunRequestedPosts;
  posts_by_ids_ingest_runs: PostsByIdsIngestRuns;
  user_handle_history: UserHandleHistory;
  users: Users;
  users_by_ids_ingest_run_requested_users: UsersByIdsIngestRunRequestedUsers;
  users_by_ids_ingest_runs: UsersByIdsIngestRuns;
  users_meta: UsersMeta;
  webhook_follow_events: WebhookFollowEvents;
  worker_heartbeats: WorkerHeartbeats;
}
