// Generated by kysely-codegen (configured via .kysely-codegenrc.json). Do not edit manually.

import type { ColumnType } from "kysely";

export type ArrayType<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S[], I[], U[]> : T[];

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type JsonPrimitive = boolean | null | number | string;
export type JsonValue = JsonPrimitive | JsonObject | JsonArray;
export interface JsonObject {
  [key: string]: JsonValue;
}
export type JsonArray = JsonValue[];

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type IngestKind =
  | "twitterio_api_user_followers"
  | "twitterio_api_user_followings"
  | "twitterio_api_users_posts"
  | "ifttt_webhook_new_follow";

export type SyncRunStatus = "success" | "in_progress" | "cancelled" | "error";

export type FollowsSyncMode = "full_refresh" | "incremental";

export type AssetSlug =
  | "segment_specified_users"
  | "segment_followers"
  | "segment_followed"
  | "segment_mutuals"
  | "segment_unreciprocated_followed"
  | "post_corpus_for_segment";

export type AssetMaterializationStatus = "success" | "in_progress" | "cancelled" | "error";

export type AssetInstanceFanoutMode = "global_per_item" | "scoped_by_source";

export type AssetEventType = "enter" | "exit";

export interface IngestEvents {
  id: Generated<bigint>;
  ingest_kind: IngestKind;
  created_at: Generated<Timestamp>;
}

export interface Users {
  id: bigint;
  handle: string | null;
  display_name: string | null;
  profile_url: string | null;
  profile_image_url: string | null;
  cover_image_url: string | null;
  bio: string | null;
  location: string | null;
  is_blue_verified: boolean | null;
  verified_type: string | null;
  is_translator: boolean | null;
  is_automated: boolean | null;
  automated_by: string | null;
  possibly_sensitive: boolean | null;
  unavailable: boolean | null;
  unavailable_message: string | null;
  unavailable_reason: string | null;
  followers_count: bigint | null;
  following_count: bigint | null;
  favourites_count: bigint | null;
  media_count: bigint | null;
  statuses_count: bigint | null;
  user_created_at: Timestamp | null;
  bio_entities: JsonValue | null;
  affiliates_highlighted_label: JsonValue | null;
  pinned_tweet_ids: ArrayType<string> | null;
  withheld_countries: ArrayType<string> | null;
  is_deleted: Generated<boolean>;
  last_ingest_event_id: bigint | null;
  last_updated_at: Timestamp | null;
  last_ingest_kind: IngestKind | null;
  handle_norm: Generated<string | null>;
}

export interface Follows {
  target_id: bigint;
  follower_id: bigint;
  is_deleted: Generated<boolean>;
}

export interface Posts {
  id: bigint;
  author_id: bigint;
  posted_at: Timestamp;
  text: string | null;
  lang: string | null;
  raw_json: JsonValue | null;
  is_deleted: Generated<boolean>;
}

export interface FollowersSyncRuns {
  ingest_event_id: bigint;
  target_user_id: bigint;
  completed_at: Timestamp | null;
  status: Generated<SyncRunStatus>;
  sync_mode: Generated<FollowsSyncMode>;
  last_api_status: string | null;
  last_api_error: string | null;
  last_http_request: JsonValue | null;
  last_http_response: JsonValue | null;
  cursor_exhausted: Generated<boolean>;
}

export interface FollowingsSyncRuns {
  ingest_event_id: bigint;
  source_user_id: bigint;
  completed_at: Timestamp | null;
  status: Generated<SyncRunStatus>;
  sync_mode: Generated<FollowsSyncMode>;
  last_api_status: string | null;
  last_api_error: string | null;
  last_http_request: JsonValue | null;
  last_http_response: JsonValue | null;
  cursor_exhausted: Generated<boolean>;
}

export interface PostsSyncRuns {
  ingest_event_id: bigint;
  completed_at: Timestamp | null;
  status: Generated<SyncRunStatus>;
  last_api_status: string | null;
  last_api_error: string | null;
  last_http_request: JsonValue | null;
  last_http_response: JsonValue | null;
  cursor_exhausted: Generated<boolean>;
  synced_since: Timestamp | null;
}

export interface PostsSyncRunTargetUsers {
  posts_sync_run_id: bigint;
  target_user_id: bigint;
}

export interface WebhookFollowEvents {
  ingest_event_id: bigint;
  target_user_id: bigint;
  follower_user_id: bigint | null;
  follower_handle: string | null;
  raw_payload: JsonValue | null;
}

export interface UsersMeta {
  id: Generated<bigint>;
  user_id: bigint;
  ingest_event_id: bigint;
  ingest_kind: IngestKind;
  updated_at: Generated<Timestamp>;
}

export interface FollowsMeta {
  id: Generated<bigint>;
  target_id: bigint;
  follower_id: bigint;
  ingest_event_id: bigint;
  ingest_kind: IngestKind;
  updated_at: Generated<Timestamp>;
}

export interface PostsMeta {
  id: Generated<bigint>;
  post_id: bigint;
  ingest_event_id: bigint;
  updated_at: Generated<Timestamp>;
}

export interface UserHandleHistory {
  id: Generated<bigint>;
  user_id: bigint;
  previous_handle: string;
  new_handle: string;
  ingest_event_id: bigint | null;
  recorded_at: Generated<Timestamp>;
}

export interface SchedulerPolicyOverrides {
  id: Generated<bigint>;
  job_id: string;
  target_id: string | null;
  cadence_seconds: bigint | null;
  jitter_seconds: number | null;
  max_parallel_per_target: number | null;
  max_retries: number | null;
  disabled: Generated<boolean>;
  reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SchedulerPlannerEvents {
  id: Generated<bigint>;
  job_id: string;
  target_id: string | null;
  target_params: string | null;
  decision: string;
  reason: string | null;
  planned_for: Timestamp | null;
  planner_run_id: string | null;
  created_at: Generated<Timestamp>;
}

export interface WorkerHeartbeats {
  service: string;
  worker_id: string;
  started_at: Generated<Timestamp>;
  last_heartbeat_at: Generated<Timestamp>;
}

export interface AssetParams {
  id: Generated<bigint>;
  asset_slug: AssetSlug;
  params_hash_version: Generated<number>;
  params_hash: string;
  fanout_source_params_hash: string | null;
  fanout_source_params_hash_version: number | null;
}

export interface SegmentSpecifiedUsersParams {
  asset_params_id: bigint;
  stable_key: string;
}

export interface SegmentFollowersParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface SegmentFollowedParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface SegmentMutualsParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface SegmentUnreciprocatedFollowedParams {
  asset_params_id: bigint;
  subject_external_id: bigint;
}

export interface PostCorpusForSegmentParams {
  asset_params_id: bigint;
  source_segment_params_id: bigint;
}

export interface AssetInstances {
  id: Generated<bigint>;
  params_id: bigint;
  asset_slug: AssetSlug;
  params_hash_version: Generated<number>;
  params_hash: string;
  current_membership_materialization_id: bigint | null;
}

export interface AssetInstanceRoots {
  id: Generated<bigint>;
  instance_id: bigint;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
}

export interface AssetInstanceFanoutRoots {
  id: Generated<bigint>;
  source_instance_id: bigint;
  target_asset_slug: AssetSlug;
  fanout_mode: AssetInstanceFanoutMode;
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
}

export interface AssetMaterializations {
  id: Generated<bigint>;
  asset_instance_id: bigint;
  asset_slug: AssetSlug;
  inputs_hash_version: Generated<number>;
  inputs_hash: string;
  dependency_revisions_hash_version: Generated<number>;
  dependency_revisions_hash: string;
  output_revision: Generated<bigint>;
  status: Generated<AssetMaterializationStatus>;
  started_at: Generated<Timestamp>;
  completed_at: Timestamp | null;
  trigger_reason: string | null;
  error_payload: JsonValue | null;
}

export interface AssetMaterializationDependencies {
  materialization_id: bigint;
  dependency_materialization_id: bigint;
}

export interface AssetMaterializationRequests {
  materialization_id: bigint;
  requested_by_materialization_id: bigint;
}

export interface PostsSyncRunRequestedByMaterializations {
  posts_sync_run_id: bigint;
  requested_by_materialization_id: bigint;
}

export interface SegmentEvents {
  id: Generated<bigint>;
  materialization_id: bigint;
  user_id: bigint;
  event_type: AssetEventType;
  recorded_at: Generated<Timestamp>;
  is_first_appearance: boolean | null;
}

export interface PostCorpusEvents {
  id: Generated<bigint>;
  materialization_id: bigint;
  post_id: bigint;
  event_type: AssetEventType;
  recorded_at: Generated<Timestamp>;
  is_first_appearance: boolean | null;
}

export interface SegmentMembershipSnapshots {
  instance_id: bigint;
  user_id: bigint;
  materialization_id: bigint;
  recorded_at: Generated<Timestamp>;
}

export interface PostCorpusMembershipSnapshots {
  instance_id: bigint;
  post_id: bigint;
  materialization_id: bigint;
  recorded_at: Generated<Timestamp>;
}

export interface SegmentSpecifiedUsersInputs {
  instance_id: bigint;
  user_external_id: bigint;
}

export interface Database {
  ingest_events: IngestEvents;
  users: Users;
  follows: Follows;
  posts: Posts;
  followers_sync_runs: FollowersSyncRuns;
  followings_sync_runs: FollowingsSyncRuns;
  posts_sync_runs: PostsSyncRuns;
  posts_sync_run_target_users: PostsSyncRunTargetUsers;
  webhook_follow_events: WebhookFollowEvents;
  users_meta: UsersMeta;
  follows_meta: FollowsMeta;
  posts_meta: PostsMeta;
  user_handle_history: UserHandleHistory;
  scheduler_policy_overrides: SchedulerPolicyOverrides;
  scheduler_planner_events: SchedulerPlannerEvents;
  worker_heartbeats: WorkerHeartbeats;
  asset_params: AssetParams;
  segment_specified_users_params: SegmentSpecifiedUsersParams;
  segment_followers_params: SegmentFollowersParams;
  segment_followed_params: SegmentFollowedParams;
  segment_mutuals_params: SegmentMutualsParams;
  segment_unreciprocated_followed_params: SegmentUnreciprocatedFollowedParams;
  post_corpus_for_segment_params: PostCorpusForSegmentParams;
  asset_instances: AssetInstances;
  asset_instance_roots: AssetInstanceRoots;
  asset_instance_fanout_roots: AssetInstanceFanoutRoots;
  asset_materializations: AssetMaterializations;
  asset_materialization_dependencies: AssetMaterializationDependencies;
  asset_materialization_requests: AssetMaterializationRequests;
  posts_sync_run_requested_by_materializations: PostsSyncRunRequestedByMaterializations;
  segment_events: SegmentEvents;
  post_corpus_events: PostCorpusEvents;
  segment_membership_snapshots: SegmentMembershipSnapshots;
  post_corpus_membership_snapshots: PostCorpusMembershipSnapshots;
  segment_specified_users_inputs: SegmentSpecifiedUsersInputs;
}
